#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyBookStore.Resource", IsApplication=true)]

namespace MyBookStore
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int mybookstorelogo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int bookAvailableTextView = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int bookDescriptionTextView = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int bookNameTextView = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int bookPriceTextView = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int booksListView = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int buttonAboutApp = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int buttonViewBooks = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int buttonViewCart = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int fragmentContainer = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int imageView1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int space1 = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int textAvailable = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int textBookName = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textCategory = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int textDescription = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int textPrice = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutApp = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BookDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BookRowView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CategoryAFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CategoryBFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CategoryCFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FavoriteBooksFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ViewBooks = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ViewCart = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int AboutAppActivityContent = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int AboutAppActivityHeading = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int ButtonAboutApp = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int ButtonViewBooks = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ButtonViewCart = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
